# Generated by Django 4.2.3 on 2023-07-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_since_published',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
