# Generated by Django 4.2.3 on 2023-07-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_since_published',
        ),
    ]
