# Generated by Django 4.2.3 on 2023-07-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_article_time_since_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pages/articles/'),
        ),
    ]
