# Generated by Django 4.2.3 on 2023-07-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_event_article_category_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
