# Generated by Django 4.2.3 on 2023-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Москва', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
