# Generated by Django 4.2.3 on 2023-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_article_source_alter_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(),
        ),
    ]
