# Generated by Django 4.2.3 on 2023-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_article_description_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='https://4.downloader.disk.yandex.ru/preview/516b1342be2ea4076182b935a87de50d4df247c170b7bf037536380d6c31ba3a/inf/0adu6mDS9Y3baDoe0hQ1Fj_X2xxLEXRg5PYmGnRaB_S39dybksklX4xxu8bkoa242xY0nlE-M4KNhAARZSPpIw%3D%3D?uid=1452166553&filename=Frame%201.jpg&disposition=inline&hash=&limit=0&content_type=image%2Fjpeg&owner_uid=1452166553&tknv=v2&size=4320x2124', null=True),
        ),
    ]
